name: Standard CI

# Trigger : 
on: push

jobs:
  build-test:
    name: Build, Test and Deploy
    # runs on sets up V env 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Run lint
        run: npm run lint 

      - name: Run Build
        run: npm run build

      - name: Run test
        run: npm run test

      - name: Run Deploy
        run: npm run deploy
